# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  # dependsOn:
  #  - name: external-secrets-stores
  path: ./kubernetes/main/apps/flux-system/tf-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tf-controller
      namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
#Will be enabled to provision specific stuff on this cluster
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: tf-controller-terraforms
#   namespace: flux-system
# spec:
#   dependsOn:
#     #   - name: external-secrets-stores
#     - name: tf-controller
#   path: ./kubernetes/main/apps/flux-system/tf-controller/terraforms
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-ops
#   interval: 30m
#   retryInterval: 1m
#   timeout: 3m
---

