---
# yaml-language-server: $schema=https://crd.movishell.pl/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: &cluster home-ops
spec:
  backupOwnerReference: self
  cluster:
    name: *cluster
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: garage-home-ops
  schedule: "0 0 5 * * *" 
---
# yaml-language-server: $schema=https://crd.movishell.pl/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: home-ops-cold-backup
spec:
  schedule: "0 0 3 * * *" # at 3 AM every day
  backupOwnerReference: self
  cluster:
    name: home-ops
  method: volumeSnapshot
  online: false