---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rook-ceph-dashboard
  annotations:
    # Hajimari
    hajimari.io/appName: "Rook"
    hajimari.io/icon: mdi:chess-rook
    # External DNS

    # Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: Ceph
    gethomepage.dev/icon: https://miro.medium.com/v2/resize:fit:820/1*gJQ7_l2Q03aX7cYeCYpiFQ.png
    gethomepage.dev/description: Ceph Dashboard
    gethomepage.dev/siteMonitor: http://rook-ceph-mgr-dashboard.rook-ceph:7000
    gethomepage.dev/pod-selector: >-
      app.kubernetes.io/name in (ceph-mgr)
spec:
  hostnames: ["rook.rafaribe.com"]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: rook-ceph-mgr-dashboard
          namespace: rook-ceph
          port: 7000
