apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/kube-system/cilium/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  postBuild:
    substitute:
      GATEWAY_MANAGEMENT: 10.0.0.1
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app cilium-config
#   namespace: flux-system
# spec:
#   path: ./kubernetes/main/apps/kube-system/cilium/config
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-ops
#   dependsOn:
#     - name: cilium
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: cert-manager
#       namespace: cert-manager
#   interval: 30m
#   retryInterval: 1m
#   timeout: 3m
#   targetNamespace: kube-system
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   postBuild:
#     substitute:
#       GATEWAY_MANAGEMENT: 10.0.0.1
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app cilium-gateway
#   namespace: flux-system
# spec:
#   path: ./kubernetes/main/apps/kube-system/cilium/gateway
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-ops
#   dependsOn:
#     - name: cilium
#   interval: 30m
#   targetNamespace: kube-system
#   retryInterval: 1m
#   timeout: 3m
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   postBuild:
#     substitute:
#       CLUSTER: main
#       EXTERNAL_DOMAIN: external
#       INTERNAL_DOMAIN: internal
#       LB_GATEWAY_EXTERNAL: 10.0.2.253
#       LB_GATEWAY_INTERNAL: 10.0.2.254
#       # Old values, kept until I remember everything
#       #LB_NGINX_EXTERNAL: 10.0.1.100
#       #LB_NGINX_INTERNAL: 10.0.1.101
