---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homebox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Homebox Database Configuration
        HBOX_DATABASE_DRIVER: sqlite3
        HBOX_MODE: production
        HBOX_MAILER_HOST: smtp-relay.services.svc.cluster.local
        HBOX_MAILER_PORT: "25"
        HBOX_MAILER_FROM: "alerts@rafaribe.com"
        # Homebox Configuration
        HBOX_WEB_MAX_UPLOAD_SIZE: "25"
  dataFrom:
    - extract:
        key: /cloudnativepg
