apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi-poller
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/monitoring/unifi-poller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
