---
# Check this blog post for details: https://jackgruber.github.io/2020-08-15-Docker-monitoring-with-Grafana/
- name: template out /etc/docker/daemon.json
  template:
    src: docker-metrics/daemon.json
    dest: /etc/docker/daemon.json
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  register: docker_metrics_daemon_json

- name: Restart Docker daemon
  shell: systemctl restart docker
  become: true
  when: docker_metrics_daemon_json.changed