---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
metadata:
  name: loki-workaround
  namespace: system-monitoring
spec:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
          value:
            readOnlyRootFilesystem: false
    target:
      kind: StatefulSet
      name: loki
      namespace: system-monitoring
