---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: &dbName "{{ .INIT_POSTGRES_DBNAME }}"
        INIT_POSTGRES_HOST: &dbHost "home-ops-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: &dbUser "{{ .INIT_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .INIT_POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: *dbUser
        POSTGRES_PASSWORD: *dbPass
        POSTGRES_SERVER: *dbHost
        POSTGRES_PORT: "5432"
        POSTGRES_DB: *dbName
        DB_ENGINE: "postgres"
        # Base Values
        BASE_URL: https://mealie.rafaribe.com
        ALLOW_SIGNUP: "false"
        AUTO_BACKUP_ENABLED: "true"
        API_DOCS: "false"
        TZ: Europe/Lisbon
        WORKERS_PER_CORE: "1"
        MAX_WORKERS: "1"
        WEB_CONCURRENCY: "1"

  dataFrom:
    - extract:
        key: /mealie
    - extract:
        key: /cloudnativepg
