---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name autobrr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Postgres Init
        # INIT_POSTGRES_HOST: &dbHost "home-ops-rw.database.svc.cluster.local"
        # INIT_POSTGRES_DBNAME: &dbName autobrr
        # INIT_POSTGRES_USER: &dbUser autobrr
        # INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        # INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Autobrr
        AUTOBRR__DATABASE_TYPE: sqlite
        # AUTOBRR__POSTGRES_DATABASE: *dbName
        # AUTOBRR__POSTGRES_HOST: *dbHost
        # AUTOBRR__POSTGRES_USER: *dbUser
        # AUTOBRR__POSTGRES_PASS: *dbPass
        # AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: /autobrr
    - extract:
        key: /cloudnativepg
