---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./audiobookshelf/ks.yaml
 # - ./booklore/ks.yaml
  - ./common/ks.yaml
  - ./calibre-web/ks.yaml
  #  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./kavita/ks.yaml
  - ./komga/ks.yaml
  - ./media-browser/ks.yaml
  - ./maintainerr/ks.yaml
  - ./navidrome/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./wizarr/ks.yaml
  - ./your-spotify/ks.yaml
