---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/alerts
  - ../../components/repos/app-template
resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./kavita/ks.yaml
  - ./komga/ks.yaml
  - ./maintainerr/ks.yaml
  - ./media-browser/ks.yaml
  - ./navidrome/ks.yaml
  - ./pinchflat/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./wizarr/ks.yaml
  - ./your-spotify/ks.yaml
