---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: rafaribe-com-tls
spec:
  refreshInterval: 24h
  updatePolicy: Replace
  deletionPolicy: Delete
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: akeyless-secret-store
  selector:
    secret:
      name: rafaribe-com-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" }}'
      tls.key: '{{ index . "tls.key" }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: rafaribe-com-tls
          property: *key
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: rafaribe-com-tls
          property: *key