---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config
  namespace: storage
  labels:
    app.kubernetes.io/name: &name pgadmin
    app.kubernetes.io/instance: *name
    #kasten-io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
