---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-srv-02
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: srv-02
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "export DISK=/dev/sda; apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $DISK; dd if=/dev/zero bs=100M count=1000 oflag=direct,dsync of=$DISK; wipefs -af $DISK; blkdiscard $DISK; partprobe $DISK;",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-srv-03
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: srv-03
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "export DISK=/dev/sda; apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $DISK; dd if=/dev/zero bs=100M count=1000 oflag=direct,dsync of=$DISK; wipefs -af $DISK; blkdiscard $DISK; partprobe $DISK;",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-srv-05
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: srv-05
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "export DISK=/dev/sda; apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $DISK; dd if=/dev/zero bs=100M count=1000 oflag=direct,dsync of=$DISK; wipefs -af $DISK; blkdiscard $DISK; partprobe $DISK;",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-tpi-1
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: tpi-1
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "export DISK=/dev/nvme0n1; apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $DISK; dd if=/dev/zero bs=100M count=1000 oflag=direct,dsync of=$DISK; wipefs -af $DISK; blkdiscard $DISK; partprobe $DISK;",
        ]
---

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-tpi-2
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: tpi-2
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "export DISK=/dev/nvme0n1; apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $DISK; dd if=/dev/zero bs=100M count=1000 oflag=direct,dsync of=$DISK; wipefs -af $DISK; blkdiscard $DISK; partprobe $DISK;",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-tpi-3
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: tpi-3
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "export DISK=/dev/nvme0n1; apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $DISK; dd if=/dev/zero bs=100M count=1000 oflag=direct,dsync of=$DISK; wipefs -af $DISK; blkdiscard $DISK; partprobe $DISK;",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-tpi-4
  namespace: kube-system
spec:
  restartPolicy: Never
  nodeName: tpi-4
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "export DISK=/dev/nvme0n1; apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all $DISK; dd if=/dev/zero bs=100M count=1000 oflag=direct,dsync of=$DISK; wipefs -af $DISK; blkdiscard $DISK; partprobe $DISK;",
        ]
---

