---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  # Cluster Specific
  CLUSTER_NAME: delta
  CLUSTER_ID: "0"
  CLUSTER_CERT: "letsencrypt-production"

  NETWORK_BGP_LB_CIDR: 10.0.6.0/24
  NETWORK_L2_UNIFI_CIDR: 10.0.1.254/32
  NETWORK_L2_BLOCKY_CIDR: 10.0.1.250/32
  NETWORK_L2_SYNCTHING_CIDR: 10.0.1.251/32
  K8S_API_ADDRESS: truenas.rafaribe.com
  K8S_CLUSTER_CIDR: 172.16.0.0/16
  K8S_SERVICE_CIDR: 172.17.0.0/16

  # Common
  GATEWAY_MANAGEMENT: 10.0.1.1
  TZ: Europe/Lisbon
  NAS_ADDRESS: 10.0.1.11
  NAS_DIR: /data/share/nfs
  NAS_BACKUP_DIR: /data/backups

  # Home Network IP's
  LB_BLOCKY: 10.0.1.250
  LB_NGINX: 10.0.6.1
  LB_SYNCTHING: 10.0.6.2
  LB_SYNCTHING_DISCOVERY: 10.0.6.3
  # Other network IP's that are not in use
  LB_K8S_GATEWAY_ADDR: 10.0.255.1
  LB_HASS: 10.0.255.3
  LB_EMQX: 10.0.255.4
  LB_HASS_CODE_SERVER: 10.0.255.5
  LB_INFLUXDB: 10.0.255.6
  LB_QBITTORRENT: 10.0.255.7
  LB_QBITTORRENT_UI: 10.0.255.8
  LB_JELLYFIN: 10.0.255.10
  LB_NUT: 10.0.255.101
  LB_VECTOR: 10.0.255.20
  LB_PGADMIN_IP: 10.0.255.102
