---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./cluster.yaml
  - ./cluster-v3.yaml
  # - ./externalsecret.yaml
  - ./scheduledbackup.yaml
  - ./objectstore.yaml
