---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  type: "oci"
  interval: 1m
  url: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
