---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
configMapGenerator:
  - name: cloudflare-proxied-networks
    files:
      - cloudflare-proxied-networks.txt
generatorOptions:
  disableNameSuffixHash: true
