---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - databases
  - default
  - kube-system
  - media
  - network-system
  - security
  #- system-upgrade
  #- system-monitoring