k8s_cluster:
  children:
    controlplanes:
      hosts:
        delta:
          ansible_host: 10.0.1.200
          ansible_user: rafaribe
          ansible_become: true
          rke2_type: server
        omega:
          ansible_host: 10.0.1.201
          ansible_user: rafaribe
          ansible_become: true
          rke2_type: server
        theta:
          ansible_host: 10.0.1.202
          ansible_user: rafaribe
          ansible_become: true
          rke2_type: server
