---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
        namespace: flux-system
      interval: 10m
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    nginxGateway:
      gatewayClassName: nginx
      image:
        repository: ghcr.io/nginxinc/nginx-gateway-fabric
        tag: 1.1.0
        pullPolicy: Always
    nginx:
    ## The NGINX image to use
    image:
      repository: ghcr.io/nginxinc/nginx-gateway-fabric/nginx
      tag: 1.0.0
      pullPolicy: Always
    service:
      create: true
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        io.cilium/lb-ipam-ips: ${LB_NGINX_GATEWAY}
