apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: one-node-cluster
  namespace: default
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 750Mi
    limits:
      cpu: 1
      memory: 750Mi
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      - port: 9092
    pandaproxyApi:
      - port: 8082
    schemaRegistry:
      port: 8081
    adminApi:
      - port: 9644
    developerMode: true
  storage:
    capacity: "15Gi"
