---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app ollama-dns-router
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *app
    template:
      data:
        PIHOLE_API_KEY: "{{ .PIHOLE_API_KEY }}"

  dataFrom:
    - extract:
        key: /pihole
