---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./actions-runner-controller.yaml
  - ./aqua.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudflare.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./dysnix.yaml
  - ./emqx.yaml
  - ./emberstack.yaml
  - ./enix.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./falco.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./headlamp.yaml
  - ./infracloudio.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./longhorn.yaml
  - ./k8s-at-home.yaml
  - ./k8s-gateway.yaml
  - ./kepler.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubernetes-sigs-metrics-server.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./kyverno.yaml
  - ./k8stz.yaml
  - ./lwolf.yaml
  - ./mayastor-chart.yaml
  - ./metallb.yaml
  - ./mojo2600.yaml
  - ./node-feature-discovery.yaml
  - ./nfs-provisioner.yaml
  - ./nginx-gateway-fabric.yaml
  - ./nvidia.yaml
  - ./openebs.yaml
  - ./opentelemetry.yaml
  - ./pascaliske.yaml
  - ./percona.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./stevehipwell.yaml
  - ./vector.yaml
  - ./xenitab.yaml
  - ./victoria.yaml
  - ./tailscale.yaml
