# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name affine
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_HOST: &dbHost "home-ops-rw.database.svc.cluster.local"
        INIT_POSTGRES_DBNAME: &dbName affine
        INIT_POSTGRES_USER: &dbUser affine
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DATABASE_URL: "postgresql://affine:{{ .POSTGRES_GENERIC_APP_PASSWORD }}@home-ops-rw.database.svc.cluster.local/affine"
        # Admin user
        AFFINE_ADMIN_EMAIL: "{{ .AFFINE_ADMIN_EMAIL }}"
        AFFINE_ADMIN_PASSWORD: "{{ .AFFINE_ADMIN_PASSWORD }}"
        # SMTP configuration
        MAILER_HOST: "smtp-relay.services.svc.cluster.local"
        MAILER_PORT: "25"
        MAILER_SENDER: "alerts@rafaribe.com"

  dataFrom:
    - extract:
        key: affine
    - extract:
        key: cloudnativepg
