---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./cloudflare-operator.yaml
  - ./local-path-provisioner.yaml
  - ./gateway-api.yaml
  - ./kubevirt-cdi.yaml
  - ./kubevirt.yaml
