---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/alerts
  - ../../components/repos/app-template
resources:
  - ./namespace.yaml
  - ./autobrr/ks.yaml
  # - ./bazarr/ks.yaml  # DISABLED: Uses ceph PVC
  - ./flaresolverr/ks.yaml
  - ./kapowarr/ks.yaml
  - ./metube/ks.yaml
  - ./omegabrr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  # - ./sonarr/ks.yaml  # DISABLED: Uses ceph PVC
