---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        REDIS_HOST: romm-dragonfly.games.svc.cluster.local
        REDIS_PORT: "6379"
        DB_HOST: &dbHost home-ops-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "romm"
        DB_PASSWD: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        DB_NAME: &dbName romm
        IGDB_CLIENT_ID: "{{ .ROMM_IGDB_CLIENT_ID }}"
        IGDB_CLIENT_SECRET: "{{ .ROMM_IGDB_CLIENT_SECRET }}"
        STEAMGRIDDB_API_KEY: "{{ .ROMM_STEAMGRIDDB_API_KEY }}"
        RETROACHIEVEMENTS_API_KEY: "{{ .ROMM_RETROACHIEVEMENTS_API_KEY }}"
        DISABLE_USERPASS_LOGIN: "false"
        OIDC_ENABLED: "true"
        OIDC_PROVIDER: authentik
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_REDIRECT_URI: https://romm.rafaribe.com/api/oauth/openid
        OIDC_SERVER_APPLICATION_URL: https://sso.rafaribe.com
        ROMM_AUTH_SECRET_KEY: "{{ .ROMM_AUTH_SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /cloudnativepg
    - extract:
        key: /romm
    - extract:
        key: /romm/oidc
