---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./common # OCI Repository
  # Flux-Kustomizations
  - ./open-webui/ks.yaml
  - ./ollama/ks.yaml
  - ./paperless-ai/ks.yaml
  - ./paperless-gpt/ks.yaml