---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: &name cloudnative-pg
  namespace: storage
spec:
  provider:
    doppler:
      project: cloudnativepg
      config: home-ops
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: flux-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudnative-pg-minio
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudnative-pg
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: MINIO_SECRET_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudnative-pg-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudnative-pg
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: POSTGRES_SUPER_PASS
