# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:LfSFGMWPSUiuCLCb,iv:ANibnb84HbVoEgM2otBGy1R7xgtNIWwCvMmFqRe1P3E=,tag:UcLiy1wMNMvvxOOA0mIeiw==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:H09vj+cnGEFxHm0o,iv:5IibJyQEPjdGcAF03bvawuXwSMsmRXFwFzWw6YHoUpg=,tag:bRNzv8L8igiQBytb0N/qTQ==,type:str]
    SECRET_GRAFANA_ADMIN: ENC[AES256_GCM,data:LJPCXec=,iv:BxQZ6MlxQuFTrmFpm8pghdaVjFHavqkVcFNUW9o/neQ=,tag:F5Kx0V0gZP+8Jhbx44+WdQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:P/ZmPEFOlVfV,iv:J/mDimflZWlzz7YdadRQiWRA/fUpUtU54wJNWid4aac=,tag:YylzS0lfUCbaF69hLHZjxw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:x58xLkdHRewIVJ6RDTXM301wmq0=,iv:4Fq9hS6O/NwEWZu2riSLCnRwA7uN6ubNEQ0bqi5xBPU=,tag:U3+pv0S5tHlbxN9mzjIf2w==,type:str]
    SECRET_CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:v0YOuYBjz/vwT5VZ3RLD26OLyqmpk1FdZkH8yxdC2BM=,iv:7fte90mQyAbn191PAkPXLpDZUOLNO4xkcxWGUOBnvKw=,tag:5ZnWhykMVMtpLAyPTl5biw==,type:str]
    SECRET_CLOUDFLARE_API: ENC[AES256_GCM,data:doXVuTUU4kgYOqB4CQjr7h5tbMF4hAM+ufdg8ShTLNmYBLGfAbSGUQ==,iv:6nYCrBtSG/fOOfbnhQ6RMkc7wA20LCsVJJzykTx+owA=,tag:DBgIHEGJb9qE8x22aTT01A==,type:str]
    SECRET_LOKI_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:ZZZry6DF1mU=,iv:fAKbD95IlRMOeqcxRTJ+uA5ImMI9iPPvJR5H8mLyycM=,tag:uqHWG+hXjjl4vt454wWXEg==,type:str]
    SECRET_LOKI_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:xCcxr3RQ9PTmREWFTWY=,iv:FMoG5CV6/aMIFtM3W/btPvAOT5vAeX3/SlEoRL6YJxg=,tag:3H7zmeSrYt4TVJ9Ohptyhw==,type:str]
    SECRET_PROMETHEUS_REMOTE_WRITE_USERNAME: ENC[AES256_GCM,data:XIoN2FqQe+s=,iv:fAPbDo9hxEBuyBIJ+idGQacod7rMIZmzApW3Ih5GuSg=,tag:3DdT+rkhmpFOYFg53zXoqA==,type:str]
    SECRET_PROMETHEUS_REMOTE_WRITE_PASSWORD: ENC[AES256_GCM,data:dxt5DJJ6JhjUudZesSk=,iv:GPeWTkLi+53aFX7dq+/o0VJwvTC9Csnzd/oH5u/4iUc=,tag:PC4lG7YZa57sLX5gcxu94w==,type:str]
    SECRET_PROMETHEUS_REMOTE_WRITE_HASH: ENC[AES256_GCM,data:GT00UzFfpP9fxCYerzUFyoj3r5QQbs9YE1lG/ZoTQvnbmQgFW1yax2GQm05m8WlgzePdWjXzPYcCGJNJ8kdk1g==,iv:xON6/Ww4GEOglP0CGHbVR1+/HH5KjztwNMlrI28lYQ8=,tag:EPiggEndak+0Uye3i9QfwQ==,type:str]
    SECRET_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:S699i0HU2FL0UQ==,iv:4NBbXf00+M0iJxVsU1y0ouZIXKVH2pZm4J4kAa6LM7U=,tag:lAAgixZpSSJNcVHdB4w9WA==,type:str]
    SECRET_FIREFLY_PASSWORD: ENC[AES256_GCM,data:n+enzkKKpJaWdEqrIeo=,iv:uztKFwkgp59Ol12YNMl2X8WQAk2RxewkjR48K98DhkA=,tag:JoQ6lumqImb+AnXmFyrt9Q==,type:str]
    SECRET_KUBECLARITY_DATABASE_PASSWORD: ENC[AES256_GCM,data:yDW+2FBFfq5/xLDyNlE=,iv:DEfsuStuhiZ4ZXDPbo9+wklY7v2s2wNkFpA+u7Fqd48=,tag:tD82qVoRTiXGuOVxX1zp8A==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:O3kCval8hWyhIZGcjOM8sXtgj9fQLCVF8pT/9scUyUH7c8df9zE4NW6FMzpeUJsH5l35kpHZByZtsQeYdmM7RCr93/fw6oRTvv8YgjHsjiMo3WgtMzzPyQDzoE0xpKCtbFOXPM6iJa3grBLl1wf6bdfDPTTTdnY4CaYE,iv:xx5ZrJSPAGELZHmu86kn9OZuxBw7MqO3+Eb6l3iPngU=,tag:vYA5gm0xD0TPcH+yGFPhZw==,type:str]
    CLUSTER_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gmDs5q7lkBANwXVw6zMlWJAzoR0ZbFJk9Memk4doL5igQNZn,iv:cm0lIgfcvlt3IxT7SykEnLJpSAgv+z+fg4CY5UUn0VI=,tag:WPYBAt4X3pPVv322u0Et0Q==,type:str]
    CLUSTER_CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:EI/iQQ+cDgl/ldT9QwkZdbiIS1ZOz7RKnVBZcUhXMNWdR7Yri0vnhvXm55E1OFrxiD2UmZVzoFSjLFhJX69LAgvAkh2Ro4l23w0UlcM0eVG+n1xOCvkswGHcfbuJX5hp6Bw2vpW/6dBlOP4rAQApiIk+MoD/lRA9xTs1IRWdWQbRjFISe7ywi+MEuww9WaImJMPLz3ao8SgScFvF5b9OUhIr9mYcp9mVGL2AOpMyp3N4LG6KPq7avg==,iv:85979DFu2BSfnop0jtyDNGLTc+Im/6Zs5WKhmhx3BGI=,tag:4LidD9L1/0YU/ZGQIgOW5A==,type:str]
    #ENC[AES256_GCM,data:IohrSbBz,iv:qfnpcQ9EfZwGyrKUYT+2ODZLgWKkkPW966o/iVqKLsY=,tag:wgcwCS7SMjCfh8JAWZzflQ==,type:comment]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:mcfMikChmLrk1DtRGtdn1Q==,iv:Ee9yVXBna4y29SfrvcZX7wIOMC+CcLDl00B73nQIDEo=,tag:PIDa1Eq38YmeZty5bbN+ng==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:iNdbDMvIEHdA65y1W9g7WvfCCL3pTtylfYPN9HgFfo4=,iv:ooAre0L+Fw+gW4GLBPFWLArKHG1D1oy1mjJt3jcFka8=,tag:XiPM65wxf8iDm8Q5m7Ca5w==,type:str]
    #ENC[AES256_GCM,data:z67NbVm2kg==,iv:COdMgEPYbTEnE9u02VSoOQrFI2CegKwytfUZ/ttt0Tk=,tag:EIpUepylPJJyQK/2jBbmtw==,type:comment]
    SECRET_FIREFLY_APPKEY: ENC[AES256_GCM,data:nS/q7K4oXFNSPmO2pY+dNElIncmHM5BxBpNFjXIHsAQ=,iv:LkPFHSBaRGsPb94e6uflmVS7JzOEsNTXbNOrEImj+pI=,tag:SbW58yek/ybMOgoSnSaU7A==,type:str]
    SECRET_PAPERLESS_USERNAME: ENC[AES256_GCM,data:ECoKM9gXqbA=,iv:edmrP9cD061wuO5NruY+6NLNf4lJLwFiUe0QRycLSVw=,tag:aFhQOsPN6sbrJIolfkIaWQ==,type:str]
    SECRET_PAPERLESS_PASSWORD: ENC[AES256_GCM,data:MzmhngmlbjsFzFg1TY8=,iv:XqqjXmv1SwlCZKuqpBZaA+0NNRdE7h7gbUVgMvfAnXk=,tag:YDbC97Pc3JRnlsjCJgzx2A==,type:str]
    #ENC[AES256_GCM,data:CNeL9/S7+KlL4Q==,iv:47+BM5Zo6oEzg3sdcVa2JSPM0JZUhHY3+dLC57jKDNU=,tag:xfga1r8LnrxCBjtOx2/rPA==,type:comment]
    AUTHENTIK_PG_PASSWORD: ENC[AES256_GCM,data:W7B194WDv1mIHuSbf7hWM/IrBoqGto9q3NC64zeky/Q=,iv:0Cv966uQGwUoztiM45JY/Ah7S7XjI0l17bzfadgNZyI=,tag:hgu4QiTE5Ilttcfk89P7Sg==,type:str]
    AUTHENTIK_SECRET: ENC[AES256_GCM,data:6G3M82z2T0XPr8qafAJPn4isxIwsmtmIhmAnsGX5ms++95COIxUeu6e/vpnxnq3U,iv:EflbU7wgA4NBMnYeB4ntLWfAuuxjfZXQpDmUtbJygno=,tag:A3KE4Rz4Ns8hGNhtwru/fA==,type:str]
    #ENC[AES256_GCM,data:dUrQ2dR4mb4=,iv:RUB6FiN5p2CDrYvDgZwJ8D6Yix3W8Qz2tZHM6cgOiDU=,tag:qz/tu5EugIOa7hRkZeu5UQ==,type:comment]
    SECRET_CALIBRE: ENC[AES256_GCM,data:LH0+rXjiwMt0s3I=,iv:DdDcLttsSCsQPeFPu+Ry2q5AJ6fKPHgtkW//p0Dp+hw=,tag:SNCYVek5uzG+EuDU7mfDag==,type:str]
    #ENC[AES256_GCM,data:ndV1Lg==,iv:EEQXnWnAIAcmN9ky7FgTkoPbLKW0GtGKPs4FCMD0+bQ=,tag:nqg5uPJbvEmbwvpO6xfQAQ==,type:comment]
    NUT_PASSWORD: ENC[AES256_GCM,data:tzCS2ayOEvgdBFmCSQg=,iv:Kcy93pr97AGiLlx8lB8In2VNZo/w0w178GYoU4ZoRbA=,tag:u0i52qXQvlwgzxzRDjtnlQ==,type:str]
    #ENC[AES256_GCM,data:Q84Y0iWjLeFj,iv:JzqwVFcTVqarH7MdqSXvNvGKzn/hHXnUts94GyVNGIQ=,tag:C6a/4GPPHdBqgBdaDpSQag==,type:comment]
    INFLUXDB_PASSWORD: ENC[AES256_GCM,data:TFsJXBH0KCLVKEkl8KVymE/Axfo=,iv:8PrVytrqZMGoyEpseHQVbLla9WmHuYNt6YrGq+caiyI=,tag:DbKlLw70FqgQB3z10UqB+A==,type:str]
    #ENC[AES256_GCM,data:zLqefd0YK+JH,iv:5BIP45cMR8CEqgDeF4ukplWbKMjxYusl5zaBr+oQb8U=,tag:VWFONYlei/32hQ+iQtejcg==,type:comment]
    REDPANDA_ADMIN_PASSWORD: ENC[AES256_GCM,data:3w/WbpzPgfGBaXRqbQz2DGdZH5k=,iv:y/7xCpnofxVnJ7vkAdYE7t6uUq9cXoST1m986XXkNkY=,tag:NrtqSQrDouAqJXi2TgyVLg==,type:str]
    #ENC[AES256_GCM,data:x9uv4p3A3Fi5CZ8=,iv:8PJ7ygDMDNJv5n0DGwVgldTI0aeKViiON/A4EB5B6pw=,tag:dO8nSa99PeRDvj/eM2rOKw==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:0FLM/SzeArYVI2u7oFvivTXoIf7yOL7zQChmJLENiy137e6fRboNng==,iv:lu6Nv5oxuBPqAcqhdzja9w9oBp0wFDFHb9bzUn4YXSs=,tag:FN9MCTxl0VDTqI4FU7pylQ==,type:str]
    #ENC[AES256_GCM,data:gP4xocOPMA==,iv:lM2ITIadNdhDoAZknQ5+wm1wpbIy5vb1aG83W0udStQ=,tag:PjKLb8aIUmlKvkY9pNIgiA==,type:comment]
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:KqPj/TbVJCXMLgc=,iv:dfXOrq9tB5KR751fPWJgvbM26Hg4vizsDLUkIkNnGvA=,tag:woccmI5xJm2UScyPqIBYGA==,type:str]
    #ENC[AES256_GCM,data:XsVzC/xQx5HkFZH8jgmdX+E7,iv:h3hT0LCGZyDVoAux/1I6Y1yvvy/aUBGoZkNCgbNyqn4=,tag:t+f4k4NsroshMGxW0kNEmQ==,type:comment]
    TAILSCALE_AUTHKEY: ENC[AES256_GCM,data:KALk2dokd4EMAWY3JufRR2arvsi4lZZ0euNnZiz00E0WgvUAMXE9hW10SQDK90QwrRIt2zUJKnqI,iv:RyMldXiUJZANRXRoboV27OiuGfDAiuQXTgFUOh6v2TU=,tag:VYDlf/yrK1l1XLdPQA2Oow==,type:str]
    UP_SECRET: ENC[AES256_GCM,data:ofBCkSn8GvPbZaQ=,iv:7KZsL2A5FIR07157Pm2yTVG8ItO8kopGRYyKPlKVz/s=,tag:Gs2Va6pg1ez8xp+tsqfRnw==,type:str]
    #ENC[AES256_GCM,data:qpVPtmrz,iv:SFN1zWMA+aEy4oE1TVyx4jfyGNdpdNTAsZFLTnctvmQ=,tag:NkQerk6H82cvzrueb3kI+Q==,type:comment]
    MIMIR_ETCD_PASSWORD: ENC[AES256_GCM,data:gJgt6Gip6TFGkyDMGaM=,iv:3KSpWQqSBq/i60eKQLKJE48ZgNcP9YP2q6Fsyo+lfNQ=,tag:lC8PT5JoC2v80d8lirIbtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c3lp878r5pt8lagcmewv6djmqac576gussyhwgv2h3a0nw9k5dq4p8erj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZzdQNVFHVnZYNG5vVS9k
            YkhyZ0VQR3lzSVZKczhIZWVjTkdrWjI0dDFnCkcwaDBkK0VOSU1RVDZwcDJNSUQz
            bmh5L0h3b3dBNjZ6YlA1WjVHUDlrQzgKLS0tIGhFUEJ4bUF0N0ZTMXhPTmpvaWhh
            bXB4VUVpd2ZIUjk0cDNuTTA2K0NabnMKIw+zdaXslGnz25BfT7FSSOHQMhXy2Kzw
            rzC3TP9zsciKVtlapqk0egiZD3tEMCmqO+LkHRTVVDa0mtAOsDTvZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T20:47:27Z"
    mac: ENC[AES256_GCM,data:5caDLq8H0eQOUt5w7AR3bxdk3ZoCuyIR2wWffuoZHi3sY7ERIUGHYnF/7Pk244F5QhHcX/LjChPrxNDqQ0csZ09fuFmcQVUzw5uOC8c/BHQDgKx706s3eq7IDfFXEdqwjBn22ZJNCDPm8JJKSA7zvKCizvMIeFvAK/tLha+sv28=,iv:cij9xH/FRoECXxxlwM4lm5E6AzFvaqlpfz7Ic+9Lnz8=,tag:E3VDqPiHsnPezxCUWJL2ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
