---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./audiobookshelf/ks.yaml
  - ./calibre/ks.yaml
  - ./calibre-web/ks.yaml
  - ./jellyfin/ks.yaml
  - ./media-browser/ks.yaml
  - ./plex/ks.yaml
