---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/alerts
  - ../../components/repos/app-template
resources:
  - ./namespace.yaml
  # - ./ollama/ks.yaml  # DISABLED: Uses ceph PVC
  - ./open-webui/ks.yaml
  - ./paperless-ai/ks.yaml
  - ./paperless-gpt/ks.yaml
