---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SONARR__API__KEY: "{{ .SONARR_API_KEY }}"
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"
        SONARR__POSTGRES__HOST: &dbHost "{{ .POSTGRES_HOST }}"
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: &dbUser sonarr
        SONARR__POSTGRES__PASSWORD: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        SONARR__POSTGRES__MAINDB: sonarr
        SONARR__POSTGRES__LOGDB: sonarr_log
        INIT_POSTGRES_DBNAME: &dbName sonarr sonarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: &dbUser *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /sonarr
    - extract:
        key: /cloudnativepg
