---
- hosts: 
  - all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: Kill rke2
      ansible.builtin.command: /usr/local/bin/rke2-killall.sh
    - name: Uninstall rke2
      ansible.builtin.command:
        cmd: /usr/local/bin/rke2-uninstall.sh
        removes: /usr/local/bin/rke2-uninstall.sh
    - name: Uninstall rke2 agent
      ansible.builtin.command:
        cmd: /usr/local/bin/rke2-agent-uninstall.sh
        removes: /usr/local/bin/rke2-agent-uninstall.sh
    - name: Gather list of CNI files to delete
      ansible.builtin.find:
        paths: /etc/cni/net.d
        patterns: "*"
      register: files_to_delete
    - name: Delete CNI files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"