---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage
spec:
  secretStoreRef:
    name: akeyless-secret-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_TUNNEL_API_KEY_HOMEPAGE }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UP_USER }}" # Shares this with Unpoller
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UP_PASSWORD }}" # Shares this with Unpoller
        HOMEPAGE_VAR_TRUENAS_APIKEY: "{{ .TRUENAS_APIKEY   }}" # Comes from /homepage
        HOMEPAGE_VAR_PIHOLE_API_KEY: "{{ .PIHOLE_API_KEY }}"
        HOMEPAGE_VAR_PIHOLE_PASSWORD: "{{ .PIHOLE_PASSWORD }}"
        HOMEPAGE_VAR_OPNSENSE_USERNAME: "{{ .OPNSENSE_USERNAME }}"
        HOMEPAGE_VAR_OPNSENSE_PASSWORD: "{{ .OPNSENSE_PASSWORD }}"
        HOMEPAGE_VAR_GOOGLE_CALENDAR_ICAL_URL: "{{ .GOOGLE_CALENDAR_ICAL_URL}}"
        HOMEPAGE_VAR_PROXMOX_API_USER: "{{ .PROXMOX_API_USER}}"
        HOMEPAGE_VAR_PROXMOX_API_USER_KEY: "{{ .PROXMOX_API_USER_KEY}}"
        ## Home
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .PROMETHEUS_TOKEN  }}"
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .PAPERLESS_API_KEY }}"
        ## Downloads
        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_KAPOWARR_TOKEN: "{{ .KAPOWARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}" #
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}" #
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .READARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_API_KEY }}"
        ## Media
        HOMEPAGE_VAR_JELLYFIN_TOKEN: "{{ .JELLYFIN_API_KEY }}"
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        HOMEPAGE_VAR_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        ## Observability
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GF_SECURITY_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GF_SECURITY_ADMIN_PASSWORD }}"
        ## Location
        HOMEPAGE_VAR_LATITUDE: "{{ .LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .LONGITUDE }}"
        # Authentik
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .BOOTSTRAP_TOKEN }}"
        # Lubelogger
        HOMEPAGE_VAR_LUBELOG_USERNAME: "{{ .LUBELOG_USERNAME }}"
        HOMEPAGE_VAR_LUBELOG_PASSWORD: "{{ .LUBELOG_PASSWORD }}"
        # Audiobookshelf - Comes from /homepage as theres no need to setup a secret just for that
        HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN: "{{ .AUDIOBOOKSHELF_API_KEY }}"
        # Kavita
        HOMEPAGE_VAR_KAVITA_USERNAME: "{{ .KAVITA_USERNAME }}"
        HOMEPAGE_VAR_KAVITA_PASSWORD: "{{ .KAVITA_PASSWORD }}"
        # Komga
        HOMEPAGE_VAR_KOMGA_USERNAME: "{{ .KOMGA_USERNAME }}"
        HOMEPAGE_VAR_KOMGA_PASSWORD: "{{ .KOMGA_PASSWORD }}"
        # Immich
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        # Miniflux
        HOMEPAGE_VAR_MINIFLUX_API_KEY: "{{ .MINIFLUX_API_KEY }}"
        # Tandoor
        HOMEPAGE_VAR_TANDOOR_API_KEY: "{{ .TANDOOR_API_KEY }}"
        # Mealie
        HOMEPAGE_VAR_MEALIE_API_KEY: "{{ .MEALIE_API_KEY }}"
        # Home Assistant
        HOMEPAGE_VAR_HOMEASSISTANT_KEY: "{{ .HASS_API_KEY }}"
        # Jellyseerr
        HOMEPAGE_VAR_JELLYSEERR_TOKEN: "{{ .JELLYSEERR_API_KEY }}"
        # Calibre
        HOMEPAGE_VAR_CALIBRE_USERNAME: "{{ .CALIBRE_WEB_USERNAME }}"
        HOMEPAGE_VAR_CALIBRE_PASSWORD: "{{ .CALIBRE_WEB_PASSWORD }}"
        # Navidrome
        HOMEPAGE_VAR_NAVIDROME_SALT: "{{ .NAVIDROME_SALT}}"
        HOMEPAGE_VAR_NAVIDROME_USERNAME: "{{ .NAVIDROME_USERNAME}}"
        HOMEPAGE_VAR_NAVIDROME_API_KEY: "{{ .NAVIDROME_API_KEY }}"
        # 
        HOMEPAGE_VAR_HOMEBOX_USERNAME : "{{ .HOMEBOX_USERNAME }}"
        HOMEPAGE_VAR_HOMEBOX_PASSWORD : "{{ .HOMEBOX_PASSWORD }}"
  dataFrom:
    - extract:
        key: /cloudflare
    - extract:
        key: /grafana
    - extract:
        key: /unifi
    - extract:
        key: /homepage
    - extract:
        key: /hass
    - extract:
        key: /readarr
    - extract:
        key: /sonarr
    - extract:
        key: /radarr
    - extract:
        key: /qbittorrent
    - extract:
        key: /prowlarr
    - extract:
        key: /sabnzbd
    - extract:
        key: /jellyfin
    - extract:
        key: /plex
    - extract:
        key: /tautulli
    - extract:
        key: /authentik
    - extract:
        key: /kavita
    - extract:
        key: /paperless
    - extract:
        key: /komga
    - extract:
        key: /overseerr
    - extract:
        key: /bazarr
    - extract:
        key: /kapowarr
    - extract:
        key: /lubelog
    - extract:
        key: /plant-it
    - extract:
        key: /immich
    - extract:
        key: /miniflux
    - extract:
        key: /tandoor
    - extract:
        key: /mealie
    - extract:
        key: /hass
    - extract:
        key: /jellyseerr
    - extract:
        key: /calibre
    - extract:
        key: /navidrome
    - extract:
        key: /pihole
    - extract:
        key: /homebox