---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./dysnix.yaml
  - ./emqx.yaml
  - ./emberstack.yaml
  - ./enix.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./infracloudio.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./longhorn.yaml
  - ./k8s-at-home.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubernetes-sigs-descheduler.yaml
  - ./kubernetes-sigs-metrics-server.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./kyverno.yaml
  - ./k8stz.yaml
  - ./lwolf.yaml
  - ./mayastor-chart.yaml
  - ./metallb.yaml
  - ./mojo2600.yaml
  - ./node-feature-discovery.yaml
  - ./nfs-provisioner.yaml
  - ./nginx-gateway-fabric.yaml
  - ./nvidia.yaml
  - ./openebs.yaml
  - ./openebs-cstor-chart.yaml
  - ./openebs-jiva-chart.yaml
  - ./opentelemetry.yaml
  - ./pascaliske.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./tf-controller.yaml
  - ./vector.yaml
  - ./weave-gitops.yaml
