---
originRequest:
  originServerName: external.rafaribe.com

ingress:
  - hostname: rafaribe.com
    service: https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.rafaribe.com"
    service: https://cilium-gateway-external.kube-system.svc.cluster.local
  - service: http_status:404
