# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/alerts
  - ../../components/repos/app-template

resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./exporters/ks.yaml
  - ./fluent-bit/ks.yaml
#  - ./gatus/ks.yaml  # Already commented
  # - ./grafana/ks.yaml  # DISABLED: Uses ceph PVC
  - ./kromgo/ks.yaml
  # - ./kube-prometheus-stack/ks.yaml  # DISABLED: Uses ceph PVC
  - ./silence-operator/ks.yaml
  - ./unpoller/ks.yaml
  # - ./victoria-logs/ks.yaml  # DISABLED: Uses ceph PVC
  - ./keda/ks.yaml