---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    defaultPodOptions:
      annotations:
        configmap.reloader.stakater.com/reload: blocky-config
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - blocky
                topologyKey: kubernetes.io/hostname
    controllers:
      main:
        replicas: 3
        containers:
          main:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.23
            probes:
              liveness:
                failureThreshold: 5
                periodSeconds: 10
              readiness:
                failureThreshold: 5
                periodSeconds: 10
              startup:
                initialDelaySeconds: 5
                failureThreshold: 30
                periodSeconds: 10
          ui:
            image:
              repository: ghcr.io/mozart409/blocky-frontend
              tag: v0.1.1
    service:
      main:
        enabled: true
        ports:
          http:
            port: 4000
          ui:
            port: 8002
      dns:
        enabled: true
        controller: main
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${LB_BLOCKY}
        labels:
          pool: main
        loadBalancerIP: ${LB_BLOCKY}
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
          ui:
            enabled: true
            port: 8002
            protocol: TCP
            targetPort: 8002
    serviceMonitor:
      main:
        enabled: true
        serviceName: blocky
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 30s
            scrapeTimeout: 10s
    persistence:
      config:
        enabled: true
        type: configMap
        name: blocky-config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
        readOnly: true
    configMaps:
      config:
        enabled: true
        data:
          config.yml: |
            upstream:
              default:
              - ${GATEWAY_MANAGEMENT}
            blocking:
              blackLists:
                ads:
                - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/blacklist.txt
                - https://dbl.oisd.nl/
                - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
                - http://sysctl.org/cameleon/hosts
                - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
                - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
                - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
                - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist1.txt
                - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist2.txt
                - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist3.txt
                - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/Blocklist/filter_blocklist4.txt
                - https://raw.githubusercontent.com/kodlz/pihole_easylist/main/adblock_list/adblock.hosts
                - https://raw.githubusercontent.com/herrbischoff/trackers/master/trackers.txt
                - https://raw.githubusercontent.com/herrbischoff/trackers/master/domains.txt
                - https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/smartphone-ads-tracking.txt
                - https://codeberg.org/spootle/blocklist/raw/branch/master/blocklist.txt
                - https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt
              whiteLists:
                ads:
                - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
                - https://raw.githubusercontent.com/hl2guide/Filterlist-for-AdGuard/master/filter_whitelist.txt
                - https://raw.githubusercontent.com/buvis/clusters/main/cluster-home/operations/network/blocky/whitelist.txt
              clientGroupsBlock:
                default:
                - ads
            clientLookup:
              upstream: ${GATEWAY_MANAGEMENT}
            prometheus:
              enable: true
              path: /metrics
            httpPort: 4000
            logLevel: info
            customDNS:
              mapping:
                hc.rafaribe.site: 10.0.5.10
                syncthing.rafaribe.site: 10.0.5.10
                theme-park.rafaribe.com: 10.0.5.10
