---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret pgadmin-secret-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config_local.py: |-
          AUTHENTICATION_SOURCES = ['oauth2', 'internal']
          MASTER_PASSWORD_REQUIRED = False
          OAUTH2_CONFIG = [{
              'OAUTH2_NAME': 'Authentik',
              'OAUTH2_DISPLAY_NAME': 'Authentik',
              'OAUTH2_CLIENT_ID': "{{ .OIDC_CLIENT_ID }}",
              'OAUTH2_CLIENT_SECRET': "{{ .OIDC_CLIENT_SECRET }}",
              'OAUTH2_TOKEN_URL': 'https://sso.rafaribe.com/application/o/token/',
              'OAUTH2_AUTHORIZATION_URL': 'https://sso.rafaribe.com/application/o/authorize/',
              'OAUTH2_USERINFO_ENDPOINT': 'https://sso.rafaribe.com/application/o/userinfo/',
              'OAUTH2_SERVER_METADATA_URL': 'https://sso.rafaribe.com/application/o/pgadmin/.well-known/openid-configuration',
              'OAUTH2_API_BASE_URL': 'https://sso.rafaribe.com/',
              'OAUTH2_SCOPE': 'openid email profile',
              'OAUTH2_BUTTON_COLOR': '#5E93D9',
              'OAUTH2_AUTO_CREATE_USER': True,
              'OAUTH2_ICON': 'lock'
          }]
        pgpass: |
          home-ops-rw.database.svc.cluster.local:5432:postgres:postgres:"{{.POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /pgadmin
    - extract:
        key: /pgadmin/oidc
    - extract:
        key: /cloudnativepg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret pgadmin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .PGADMIN_DEFAULT_EMAIL }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_DEFAULT_PASSWORD }}"
  dataFrom:
    - extract:
        key: /pgadmin
