---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # General
        SECRET_KEY: "{{ .TANDOOR_SECRET_KEY }}"
        # Database
        DB_ENGINE: django.db.backends.postgresql
        POSTGRES_HOST: &dbHost home-ops-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: &dbName tandoor
        POSTGRES_USER: &dbUser "{{ .TANDOOR_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Email
        EMAIL_HOST: "smtp-relay-noreply.services.svc.cluster.local"
        EMAIL_PORT: "25"
        EMAIL_USE_SSL: "1"
        DEFAULT_FROM_EMAIL: "noreply@rafaribe.com"
        ACCOUNT_EMAIL_SUBJECT_PREFIX: "[Rafaribe Recipes]"
        # OpenId Connect
        SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
        SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"SERVERS":[{"id":"authentik","name":"rafaribe.com","server_url":"https://sso.rafaribe.com/application/o/tandoor/.well-known/openid-configuration","token_auth_method":"client_secret_basic","APP":{"client_id":"{{ .OIDC_CLIENT_ID }}","secret":"{{ .OIDC_CLIENT_SECRET }}"}}]}}'
  dataFrom:
    - extract:
        key: /tandoor
    - extract:
        key: /tandoor/oidc
    - extract:
        key: /cloudnativepg