---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &token github-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *token
    template:
      engineVersion: v2
      data:
        token: "{{ .FLUX_GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: /flux
