---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./cyberchef/ks.yaml
  - ./hajimari/ks.yaml
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml
  - ./kitchenowl/ks.yaml
  - ./kubernetes-schemas/ks.yaml
  - ./linkding/ks.yaml
  - ./littlelink/ks.yaml
  - ./lubelog/ks.yaml
  - ./mealie/ks.yaml
  - ./miniflux/ks.yaml
  - ./netboot/ks.yaml
  - ./paperless/ks.yaml
  - ./radicale/ks.yaml
  - ./searxng/ks.yaml
  - ./silverbullet/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./tandoor/ks.yaml
  - ./thelounge/ks.yaml
  - ./vikunja/ks.yaml
