---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: redpanda-crds-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/redpanda-data/redpanda
  ref:
    # renovate: datasource=github-releases depName=/redpanda-data/redpanda versioning=loose
    tag: v22.1.3
  ignore: |
    # exclude all
    /*
    # path to crds
    !/src/go/k8s/config/crd/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: redpanda-crds
  namespace: flux-system
spec:
  interval: 15m
  prune: false
  sourceRef:
    kind: GitRepository
    name: redpanda-crds-source
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clusters.redpanda.vectorized.io
