---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        READARR__API__KEY: "{{ .READARR_API_KEY }}"
        READARR__AUTH__APIKEY: "{{ .READARR_API_KEY }}"
        READARR__POSTGRES__HOST: &dbHost "{{ .POSTGRES_HOST }}"
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: &dbUser readarr
        READARR__POSTGRES__PASSWORD: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        READARR__POSTGRES__MAINDB: readarr
        READARR__POSTGRES__LOGDB: readarr_log
        READARR__POSTGRES__CACHEDB: readarr_cache
        INIT_POSTGRES_DBNAME: &dbName readarr readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: &dbUser *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: /readarr
    - extract:
        key: /cloudnativepg
