---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name linkding
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        #Init Db
        INIT_POSTGRES_HOST: &dbHost home-ops-rw.database.svc.cluster.local
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .INIT_POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: &dbUser "{{ .INIT_POSTGRES_USER }}"
        INIT_POSTGRES_DBNAME: &dbName "{{ .LD_DB_DATABASE }}"
        # Linkding Database
        LD_DB_DATABASE: *dbName
        LD_DB_ENGINE: postgres
        LD_DB_HOST: *dbHost
        LD_DB_PASSWORD: *dbPass
        LD_DB_USER: *dbUser
        # General Configuration
        LD_SUPERUSER_NAME: "{{ .LD_SUPERUSER_NAME }}"
        LD_SUPERUSER_PASSWORD: "{{ .LD_SUPERUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: /linkding
    - extract:
        key: /cloudnativepg