---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name linkding
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Database Configuration
        LD_DB_ENGINE: sqlite
        # General Configuration
        LD_SUPERUSER_NAME: "{{ .LD_SUPERUSER_NAME }}"
        LD_SUPERUSER_PASSWORD: "{{ .LD_SUPERUSER_PASSWORD }}"
        # OIDC Configuration
        LD_ENABLE_OIDC: "True"
        OIDC_OP_AUTHORIZATION_ENDPOINT: "https://sso.rafaribe.com/application/o/authorize/"
        OIDC_OP_TOKEN_ENDPOINT: "https://sso.rafaribe.com/application/o/token/"
        OIDC_OP_USER_ENDPOINT: "https://sso.rafaribe.com/application/o/userinfo/"
        OIDC_OP_JWKS_ENDPOINT: "https://sso.rafaribe.com/application/o/linkding/jwks/"
        OIDC_RP_CLIENT_ID : "{{ .OIDC_CLIENT_ID }}"
        OIDC_RP_CLIENT_SECRET : "{{ .OIDC_CLIENT_SECRET }}"

  dataFrom:
    - extract:
        key: /linkding
    - extract:
        key: /linkding/oidc