---
name: "Schedule - Check links"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - "docs/**.md"

jobs:
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        id: lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress .
          output: ./lychee.md
          format: markdown

      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@v1
        with:
          state: open
          labels: |
            link-checker

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Dashboard
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee.md
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            link-checker
