---
name: "Broken Link Check"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@86576b355dd19da0519e0bdb63d8edb5bcf76a25 # v1.7.0
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Scan for broken links
        uses: lycheeverse/lychee-action@eeb9cb63fe093e4d17e5853314dbf862bb35f28d # v1.9.2
        id: lychee
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        with:
          args: --verbose --no-progress --exclude-mail './**/*.md'

      - name: Find Link Checker Issue
        id: broken-link-check-issue
        uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2.3.0
        with:
          state: open
          labels: broken-links

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94 # v5.0.0
        with:
          title: Broken links detected ðŸ”—
          issue-number: "${{ steps.broken-link-check-issue.outputs.issue-number }}"
          content-filepath: ./lychee.md
          token: "${{ steps.app-token.outputs.token }}"
          labels: broken-links
