---
# Check this blog post for details: https://jackgruber.github.io/2020-08-15-Docker-monitoring-with-Grafana/
- name: template out /etc/docker/daemon.json
  template:
    src: docker-metrics/daemon.json
    dest: /etc/docker/daemon.json
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  register: docker_metrics_daemon_json

- name: Restart Docker daemon
  shell: systemctl restart docker
  become: true
  when: docker_metrics_daemon_json.changed

- set_fact:
    cmdline_txt_path: /boot/cmdline.txt

- include_tasks: cmdline/cmdline.yml
  vars:
    key: cgroup_enable
    value: memory
    update: false
    # will add the argument if the key-value-pair doesn't exist
  register: cgroup_memory_enable_register

- include_tasks: cmdline/cmdline.yml
  vars:
    key: cgroup_enable
    value: cpuset
    update: false
  register: cgroup_cpuset_enable_register
- include_tasks: cmdline/cmdline.yml
  vars:
    key: cgroup_memory
    value: 1
    update: true
    # will replace the value of the first matching key, if found;
    # will add it if it's not found
  register: cgroup_memory_1_register

- name: reboot
  debug:
    msg: "reboot required for {{ ansible_hostname }}"
  #reboot:
  when: cgroup_memory_enable_register.changed or cgroup_cpuset_enable_register.changed or cgroup_memory_1_register.changed
