- name: template out docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  register: docker_compose

- name: docker-compose up
  shell: docker-compose -f /home/{{ ansible_user }}/docker-compose.yml up -d --remove-orphans
  when: docker_compose.changed
- name: template out docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  register: docker_compose

- name: docker-compose up
  shell: docker-compose -f /home/{{ ansible_user }}/docker-compose.yml up -d --remove-orphans
  when: docker_compose.changed